version: "3.8"

networks:
  default:
    driver: bridge

services:

  mongo:
    image: mongo:4.2.16-bionic
    restart: unless-stopped
    ports:
      - "27018:27017"

  service:
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8085:8085"
    build: .
    image: majorchork/gamegroup:v1
    environment:
      PORT: 8085
      JWT_SECRET: 123456qwerty
      MONGO_URI: mongodb://mongo:27017